include:
  - board: eyelash_corne_right
    shield: nice_view_adapter nice_view_gem
    artifact-name: eyelash_corne_studio_right
  - board: eyelash_corne_left
    shield: nice_view_adapter nice_view_gem
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: eyelash_corne_studio_left
  - board: eyelash_corne_left
    shield: settings_reset