manifest:
  remotes:
    - name: incedius
      url-base: https://github.com/incedius
  projects:
    - name: zmk
      remote: incedius
      revision: main
      import: app/west.yml
  self:
    path: config

